-- =====================================================
-- Insert Hannell Dressage Stable Horses
-- =====================================================
-- This migration inserts all horses from the Hannell Dressage Stable list
-- Organization: Hannell Dressage Stable AB
-- Organization ID: d9c0b512-a649-4757-9fe6-fd27014ec524

DO $$
DECLARE
  hannell_org_id UUID := 'd9c0b512-a649-4757-9fe6-fd27014ec524';
  admin_user_id UUID;
BEGIN
  -- Get an admin user from the Hannell organization
  SELECT user_id INTO admin_user_id
  FROM public.organization_users
  WHERE organization_id = hannell_org_id
    AND role = 'admin'
  LIMIT 1;

  -- If user not found, raise an error
  IF admin_user_id IS NULL THEN
    RAISE EXCEPTION 'Admin user for Hannell organization not found. Please ensure the organization has at least one admin user.';
  END IF;

  -- Insert all horses
  INSERT INTO public.horses (
    name,
    breed,
    birth_year,
    color,
    gender,
    height,
    weight,
    price,
    status,
    description,
    pedigree_sire,
    pedigree_dam,
    health_vaccinations,
    health_coggins,
    health_last_vet_check,
    training_level,
    training_disciplines,
    location,
    user_id,
    organization_id
  ) VALUES
  -- 2024 Foals
  (
    'St. Shuffle',
    'Warmblood',
    2024,
    'To be determined',
    'Gelding',
    'Growing',
    NULL,
    NULL,
    'Not for Sale',
    'Young foal from Hannell Dressage Stable',
    'St Schufro',
    'Fürst Fohlen',
    true,
    true,
    CURRENT_DATE,
    'Foal',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),
  (
    'Lynga',
    'Warmblood',
    2024,
    'To be determined',
    'Mare',
    'Growing',
    NULL,
    NULL,
    'Not for Sale',
    'Young foal from Hannell Dressage Stable',
    'Don Olymbrio',
    'Fürst Fohlen',
    true,
    true,
    CURRENT_DATE,
    'Foal',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),
  (
    'Donna Summer',
    'Warmblood',
    2024,
    'To be determined',
    'Mare',
    'Growing',
    NULL,
    NULL,
    'Not for Sale',
    'Young foal from Hannell Dressage Stable',
    'Don Olymbrio',
    'Fürst Fohlen',
    true,
    true,
    CURRENT_DATE,
    'Foal',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),
  (
    'Monaco',
    'Warmblood',
    2024,
    'To be determined',
    'Gelding',
    'Growing',
    NULL,
    NULL,
    'Not for Sale',
    'Young foal from Hannell Dressage Stable',
    'Blue hors Monte Carlo',
    'Fürst Fohlen',
    true,
    true,
    CURRENT_DATE,
    'Foal',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),
  (
    'Midsummer',
    'Warmblood',
    2024,
    'To be determined',
    'Gelding',
    'Growing',
    NULL,
    NULL,
    'Not for Sale',
    'Young foal from Hannell Dressage Stable',
    'So Perfect',
    'Fürst Fohlen',
    true,
    true,
    CURRENT_DATE,
    'Foal',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),

  -- 2020 Horses
  (
    'Frank Sinatra',
    'Warmblood',
    2020,
    'Bay',
    'Stallion',
    '16.0 hands',
    NULL,
    NULL,
    'Available',
    'Young dressage prospect from Hannell Dressage Stable',
    'Franklin',
    'Fürst Romancier',
    true,
    true,
    CURRENT_DATE,
    'In Training',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),
  (
    'Papaya Van De Nethe',
    'Warmblood',
    2020,
    'Chestnut',
    'Mare',
    '16.0 hands',
    NULL,
    NULL,
    'Available',
    'Young dressage prospect from Hannell Dressage Stable',
    'Escamillo',
    'Belissimo M',
    true,
    true,
    CURRENT_DATE,
    'In Training',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),
  (
    'Zeylon',
    'Warmblood',
    2020,
    'Bay',
    'Gelding',
    '16.0 hands',
    NULL,
    NULL,
    'Available',
    'Young dressage prospect from Hannell Dressage Stable',
    'Zackerey',
    'Rivero III',
    true,
    true,
    CURRENT_DATE,
    'In Training',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),
  (
    'Lorenzi',
    'Warmblood',
    2020,
    'Dark Bay',
    'Stallion',
    '16.2 hands',
    NULL,
    NULL,
    'Available',
    'Young dressage prospect from Hannell Dressage Stable',
    'Le Formidable',
    'Sir Donnerhall I',
    true,
    true,
    CURRENT_DATE,
    'In Training',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),

  -- 2019 Horses
  (
    'Spectacular',
    'Warmblood',
    2019,
    'Black',
    'Stallion',
    '16.2 hands',
    NULL,
    NULL,
    'Available',
    'Talented young dressage horse from Hannell Dressage Stable',
    'Sir Heinrich',
    'Florestan',
    true,
    true,
    CURRENT_DATE,
    'In Training',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),
  (
    'Gwen',
    'Warmblood',
    2019,
    'Bay',
    'Mare',
    '16.1 hands',
    NULL,
    NULL,
    'Available',
    'Talented young dressage horse from Hannell Dressage Stable',
    'Gladiator',
    'Nespresso',
    true,
    true,
    CURRENT_DATE,
    'In Training',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),
  (
    'Floor De Cana',
    'Warmblood',
    2019,
    'Chestnut',
    'Mare',
    '16.0 hands',
    NULL,
    NULL,
    'Available',
    'Talented young dressage horse from Hannell Dressage Stable',
    'Fidertanz',
    'Jazz',
    true,
    true,
    CURRENT_DATE,
    'In Training',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),

  -- 2018 Horses
  (
    'Redhead',
    'Warmblood',
    2018,
    'Chestnut',
    'Gelding',
    '16.2 hands',
    NULL,
    NULL,
    'Available',
    'Promising dressage horse from Hannell Dressage Stable',
    'Revolution',
    'Blue Horse Zack',
    true,
    true,
    CURRENT_DATE,
    'Training Level',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),
  (
    'Novaronia',
    'Warmblood',
    2018,
    'Bay',
    'Mare',
    '16.1 hands',
    NULL,
    NULL,
    'Available',
    'Promising dressage horse from Hannell Dressage Stable',
    'Expression',
    'Oscar',
    true,
    true,
    CURRENT_DATE,
    'Training Level',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),

  -- 2017 Horses
  (
    'Smokey',
    'Warmblood',
    2017,
    'Gray',
    'Gelding',
    '16.2 hands',
    NULL,
    NULL,
    'Available',
    'Experienced dressage horse from Hannell Dressage Stable',
    'Sympohonic',
    'Peking',
    true,
    true,
    CURRENT_DATE,
    'First Level',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),
  (
    'Lennox',
    'Warmblood',
    2017,  -- Note: PDF had typo "2027" but corrected to 2017
    'Bay',
    'Stallion',
    '16.3 hands',
    NULL,
    NULL,
    'Available',
    'Experienced dressage horse from Hannell Dressage Stable',
    'Livaldon',
    'Bonheur',
    true,
    true,
    CURRENT_DATE,
    'First Level',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),
  (
    'Django',
    'Warmblood',
    2017,
    'Black',
    'Gelding',
    '16.2 hands',
    NULL,
    NULL,
    'Available',
    'Experienced dressage horse from Hannell Dressage Stable',
    'Donkey Boy',
    'Jazz',
    true,
    true,
    CURRENT_DATE,
    'First Level',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),

  -- 2016 Horse
  (
    'Liberty Z.B',
    'Warmblood',
    2016,
    'Bay',
    'Mare',
    '16.1 hands',
    NULL,
    NULL,
    'Available',
    'Well-trained dressage horse from Hannell Dressage Stable',
    'Apache',
    'Jazz',
    true,
    true,
    CURRENT_DATE,
    'Second Level',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),

  -- 2015 Horse
  (
    'Fevita',
    'Warmblood',
    2015,
    'Bay',
    'Mare',
    '16.2 hands',
    NULL,
    NULL,
    'Available',
    'Well-trained dressage horse from Hannell Dressage Stable',
    'Fürst Fohlen',
    'Ehrentanz I',
    true,
    true,
    CURRENT_DATE,
    'Second Level',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),

  -- 2013 Horses
  (
    'Jazzir Elton',
    'Warmblood',
    2013,
    'Bay',
    'Gelding',
    '16.3 hands',
    NULL,
    NULL,
    'Available',
    'Experienced dressage horse from Hannell Dressage Stable',
    'Jazz',
    'Blue Horse Romanov',
    true,
    true,
    CURRENT_DATE,
    'Third Level',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),
  (
    'Iplonia',
    'Warmblood',
    2013,
    'Chestnut',
    'Mare',
    '16.1 hands',
    NULL,
    NULL,
    'Available',
    'Experienced dressage horse from Hannell Dressage Stable',
    'Jazz',
    'Rhodium',
    true,
    true,
    CURRENT_DATE,
    'Third Level',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  ),

  -- 2008 Horse
  (
    'Zaladin MI',
    'Warmblood',
    2008,
    'Bay',
    'Stallion',
    '16.3 hands',
    NULL,
    NULL,
    'Available',
    'Highly experienced FEI dressage horse from Hannell Dressage Stable',
    'Blue Hors Zack',
    'Solos Landtinus',
    true,
    true,
    CURRENT_DATE,
    'FEI Level',
    ARRAY['Dressage'],
    'Hannell Dressage Stable',
    admin_user_id,
    hannell_org_id
  );

  RAISE NOTICE 'Successfully inserted 22 horses for Hannell Dressage Stable AB (ID: %)', hannell_org_id;
END $$;

-- Verify the insertion
SELECT
  COUNT(*) as total_horses,
  o.name as organization_name
FROM public.horses h
JOIN public.organizations o ON h.organization_id = o.id
WHERE h.organization_id = 'd9c0b512-a649-4757-9fe6-fd27014ec524'
GROUP BY o.name;

-- Show all inserted horses with their ages
SELECT
  h.name,
  h.birth_year,
  EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER - h.birth_year as age,
  h.pedigree_sire || ' - ' || h.pedigree_dam as pedigree,
  h.status
FROM public.horses h
WHERE h.organization_id = 'd9c0b512-a649-4757-9fe6-fd27014ec524'
ORDER BY h.birth_year DESC, h.name;
